### ISSUE TITLE
Remove all old data

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#1]
In order to build the federal instance of NepalMap, we should remove all of the data, views and supporting code for the old data sets. This includes:

## General Guidelines
SQL files for data 
table definitions 
View definitions 
Profile sections (see the profile definitions in `nepalmap_app/wazimap_np/`)
Geographic data files

## Specifics
Here are some things that need to be removed:

- all files in https://github.com/Code4Nepal/nepalmap_federal/tree/dev/sql
- all files in https://github.com/Code4Nepal/nepalmap_federal/tree/dev/sql/simpletables
- all `.geojson` and `.topojson` files in https://github.com/Code4Nepal/nepalmap_federal/tree/dev/wazimap_np/static/geo
- all files in https://github.com/Code4Nepal/nepalmap_federal/tree/dev/wazimap_np/templates/profile/sections
- all of the `.py` files in https://github.com/Code4Nepal/nepalmap_federal/tree/dev/wazimap_np **except** `__init.__py`, `profiles.py`, `settings.py` and `tables.py`

These files need cleaning up:

- https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/templates/profile/profile_detail.html#L10-L19 needs all references to the profile html files removed.
- https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/profiles.py needs all of the `get_<some_profile_name>_profile` methods removed, **except** the `get_census_profile` method.
- https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/profiles.py needs all imports from wazimap_np removed.
- https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/profiles.py needs the `PROFILE_SECTIONS` removed.
- https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/tables.py needs all `FieldTable` and `SimpleTable` definitions removed.

**Comment by ravinepal** [comment]
It'd be great for someone on the team to lead on this issue. 

@Beegrekokto, @soneeka, @sunitagajurel, @crackjack, @theonlyNischal   - pls let us know if one of you are interested.

**Comment by openrijal** [comment]
I could take this one, but need more information on what exactly needs to be removed, may be a little walk-through of the existing app would help. cc: @ravinepal @cliftonmcintosh

**Comment by cliftonmcintosh** [comment]
@crackjack 

The description has been updated.

**Comment by openrijal** [comment]
what about the sqls in simpletables folder? @cliftonmcintosh

**Comment by cliftonmcintosh** [comment]
Yes, those, too, @crackjack. Thanks for catching that. I've updated the description.

**Comment by openrijal** [comment]
cannot remove `PROFILE_SECTIONS` in [profiles.py](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/profiles.py) without harming the usage in `get_census_profile()`, cannot keep them either because then the for loop is useless, I don't see much value around keeping the function there.

**Comment by cliftonmcintosh** [comment]
@crackjack 

That's fine. We can bring it back when we need it later.

**Comment by openrijal** [comment]
do you mean remove `get_census_profile()` as well or just comment it out for now?

**Comment by openrijal** [comment]
I feel like something like slack could leverage the communications here.

**Comment by cliftonmcintosh** [comment]
At your discretion. And yes, Slack would be good. We do have a Slack. https://codefornepal.slack.com/

**Comment by cliftonmcintosh** [comment]
I'm not sure how to get invited. Maybe @ravinepal can help with that.

**Comment by openrijal** [comment]
Sent a PR.

**Comment by openrijal** [comment]
sorry didn't realize that `nepalmap_app` and `nepalmap_federal` were two different repos.

I have to fork the `nepalmap_federal` repo and send a pull request there.

**Comment by cliftonmcintosh** [comment]
correct, @crackjack
