### ISSUE TITLE
National Parks generate an error

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#100]
When selecting a geographic area for a national park, NepalMap throws an error. See, for example, https://beta.nepalmap.org/profiles/local-35099-chitawan-national-park/.

~~That is because the national parks are not present in the population.sql file. They appear to have been removed when the population was updated.~~

~~As per issue #38, population data for national parks was set to zero to handle this problem. Pull request #40 added them in, but those data are no longer there.~~

The data are present in the `geography.sql` file. See [here](https://github.com/cliftonmcintosh/nepalmap_federal/blob/4cc4b890b4df42bc0fb8bc2db0219623136e1dd8/sql/population.sql#L1536-L1537) for local area 35099, the example in the link above. I am not sure why they are not displaying correctly.

**Comment by nikeshbalami** [comment]
@pratimakandel can you give a quick look at this issues; coming weekend :)

I believe; we have represented national park correctly in both geography.sql and population.sql.

**Comment by pratimakandel** [comment]
@cliftonmcintosh @nikeshbalami 
Is this how national parks and reserves should be displayed? 
![chitwan_example](https://user-images.githubusercontent.com/39708188/72406240-8e5f0480-3729-11ea-8a02-4f880035db21.png)

**Comment by nikeshbalami** [comment]
Yes @pratimakandel

@cliftonmcintosh looks like, we have the similar error at the pre-federal version. The national parks and reserves are throwing display errors: https://nepalmap.org/profiles/vdc-2595-bardiya-national-park/

**Comment by pratimakandel** [comment]
I have created a pull request for this issue #101. Please let me know if there is anything missing. 
Thank you.

**Comment by cliftonmcintosh** [comment]
Fixed by #101 

Thank you, @pratimakandel
