### ISSUE TITLE
Update graphics on homepage of beta.nepalmap

### ISSUE THREAD

**Issue by ravinepal** [CodeforNepal/nepalmap_federal#105]
![Screen Shot 2020-01-20 at 6 47 31 AM](https://user-images.githubusercontent.com/3759081/72691928-09bd1d80-3b51-11ea-8839-aff58eb5016c.png)

Update graphics with screenshots from beta.nepalmap.org to reflect federal data. 

Here's an example: https://beta.nepalmap.org/profiles/country-NP-nepal/#literacy-by-sex

**Comment by ishandongol** [comment]
sure will look into it.

**Comment by cliftonmcintosh** [comment]
Has this issue been resolved with #106 ?

**Comment by nikeshbalami** [comment]
Yes, this has been resolved. Thank you @ishandongol :)
