### ISSUE TITLE
Correct the parent geo_codes for localities

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#16]
The parent geo_codes for localities appear to be incorrect in https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql

In spot-checking the data, I have found that the codes for the districts do not match the codes for the muncipalities that should be in each district.

I have based my comparison on personal knowledge of some districts as well as comparison of the data in https://github.com/Code4Nepal/data/tree/master/Federal%20Data/753%20Local%20Unit%20Population%20and%20HouseHold

Examples of discrepancies:
[Achham is dis-01](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L77), but municipalities (like [Sunsari](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L145)) in Achham are listed as belonging to dis-69
[Arghakhanchi is dis-02](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L78), but [Arghakhanchi municipalities are listed as belonging to dis-51](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L655-L660)
[Bhaktapur is dis-10](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L86), but [Bhaktapur muncipalities are listed as belonging to dis-26](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L361-L364)
[Dadeldhura is dis-13](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L89), but [Dadeldhura muncipalities are listed as belonging to dis-73](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/geography.sql#L873-L879)

This list is an example. It is not comprehensive. In my spot-checking, I have found no muncipalities with the correct parent code.

**Comment by ravinepal** [comment]
@cliftonmcintosh - thank you for flagging

@crackjack - may i request you to look into this when you have time

**Comment by openrijal** [comment]
@ravinepal Sure.

@cliftonmcintosh the error was in the underlying geojson file, which result faulty csv and finally faulty sql

I have fixed the issue and created a pull request in both maptools and nepalmap_federal apps

**Comment by amitness** [comment]
The pull request for this seems to be merged. Should we close this? @cliftonmcintosh

**Comment by cliftonmcintosh** [comment]
Yes, @amitness 

Closing
