### ISSUE TITLE
Create data for the `wazimap_geography` table

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#2]
Create the SQL data for the geographic units for the new federal structure.

At each level, the `geo_code` should be unique. For example, for local bodies, there can only be one local body in the entire country with a `geo_code` of "1".
Except for top-level of "Nepal", each record should include its parent's geo_code as well as the geographic level of its parent. 

Please see the [current data](https://github.com/Code4Nepal/nepalmap_app/blob/dev/sql/geography.sql) for an example of how it is structured.

In looking back at the scripts that were used 2 years ago, it appears that the geojson files were manipulated to include the correct metadata and *then* the SQL data was created from those files. If it seems like that is the way to do things this time, too, then this task should wait until after #3, #4, and #5 are complete.

See the scripts in the maptools project at https://github.com/Code4Nepal/maptools/tree/master/geo.

**Comment by openrijal** [comment]
now that there is a PR which when merged the links to `.sql` files will become non-existent, may be we can link to the sqls in `nepalmap_app` project now @cliftonmcintosh

**Comment by cliftonmcintosh** [comment]
@crackjack 

description updated

**Comment by openrijal** [comment]
how do we propose to proceed on this?

**Comment by openrijal** [comment]
now that we have geojson files with updated metadata, we should move forward to generate sql files from the geojson file, please see PR #9

**Comment by cliftonmcintosh** [comment]
The data from the PR https://github.com/Code4Nepal/maptools/pull/47 looks good to me and seems ready to be used for this issue.

**Comment by cliftonmcintosh** [comment]
@crackjack 

Do you want to take the data from https://github.com/Code4Nepal/maptools/pull/47 and add use it for the geography table for this issue?

**Comment by openrijal** [comment]
I'm sorry I was preoccupied by something. I'll create the SQL right away.

**Comment by cliftonmcintosh** [comment]
No rush! I just wanted to check and see if you wanted someone else to take this step. Your contributions have been very valuable!

**Comment by openrijal** [comment]
PR submitted https://github.com/Code4Nepal/nepalmap_federal/pull/12

**Comment by openrijal** [comment]
There is a field called square kms in the table, I kept it as it is, but there was no data for it earlier, neither there is now

I can remove that field if it is not needed and update the pull request

**Comment by ravinepal** [comment]
@cliftonmcintosh - i understand this is done. am closing the issue. apologies if i'm mistaken.
