### ISSUE TITLE
Correct the names for provinces that have adopted a name rather than a number

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#22]
Our data currently uses province numbers. However, some provinces have adopted names instead. We should update our wazimap_geography SQL data and geo data to reflect those names.

https://en.wikipedia.org/wiki/Provinces_of_Nepal

**Comment by ravinepal** [comment]
Just a thought to consider: given 4 provinces are waiting to come up with their names, for consistency purposes I'd recommend using province numbers now.  Also my hesitation is that some provinces might change their names in the near future -- so perhaps useful to wait until all provinces have names.

**Comment by devbks** [comment]
How about using the available name of the provinces for now.

**Comment by ravinepal** [comment]
this is how Gov of Nepal currently states its 7 provinces: 

Province 1
Province 2
Province 3
Gandaki Province
Province 5
Karnali Province
Province 7

https://www.nepal.gov.np/NationalPortal/EN

Let's use this format.
