### ISSUE TITLE
Determine what to do about population data for wildlife and hunting reserves and national parks

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#23]
Our geographic data includes hunting reserves, wildlife reserves and national parks, but we have no population data for those areas. Where do we get population data for them? 

[Population data](https://github.com/Code4Nepal/data/tree/master/Federal%20Data/753%20Local%20Unit%20Population%20and%20HouseHold)

**Parks and reserves without any population data**

|                    Park or Reserve                   |   District   |
|------------------------------------------|------------------|
 | Khaptad National Park                    | Achham |
 Dhorpatan Hunting Reserve                | Baglung
 Khaptad National Park                    | Bajhang
 Khaptad National Park                    | Bajura
 Parsa Wildlife Reserve                   | Bara
 Bardiya National Park                    | Bardiya
 Chitawan National Park                   | Chitwan
 Khaptad National Park                    | Doti
 Shuklaphanta National Park               | Kanchanpur
 Chitawan National Park                   | Makwanpur
 Parsa Wildlife Reserve                   | Makwanpur
 Dhorpatan Hunting Reserve                | Myagdi
 Chitawan National Park                   | Nawalparasi East
 Langtang National Park                   | Nuwakot
 Shivapuri Watershed And Wildlife Reserve | Nuwakot
 Chitwan National Park                    | Parsa
 Dhorpatan Hunting Reserve                | Rukum East
 Koshi Tappu Wildlife Reserve             | Saptari
 Koshi Tappu Wildlife Reserve             | Sunsari
 Koshi Tappu Wildlife Reserve             | Udayapur

**Comment by ravinepal** [comment]
thanks @cliftonmcintosh. if it's fine with you and team, i'd recommend using "0" if you can't use "N/A". 

would that work?

I don't believe gov has made population data publicly available for these boundaries. I can check with contacts but for the interim I would recommend moving ahead with above suggestions unless there is strong alternative preference.

**Comment by cliftonmcintosh** [comment]
@ravinepal Thank you. "N/A" is not an option. The framework requires a number for each data point.

**Comment by ravinepal** [comment]
Thanks, @cliftonmcintosh. Let's put "0" then.
