### ISSUE TITLE
Determine if Wazimap 1.0.0 would allow for the presentation of pre-federal and federal data in the same instance of NepalMap

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#30]
Wazimap 1.0 appears to allow for different data sets from different time periods. Evaluate this capability to determine if it would allow us to have one instance that presents both pre-federal and federal data. 

The South Africa Wazimap is here: https://wazimap.co.za/profiles/country-ZA-south-africa/
The release docs are here: https://wazimap.readthedocs.io/en/latest/version_history.html
A blog post about the new South Africa data: https://openup.org.za/articles/wazimap-2016-update.html

The outcome of this issue is to determine whether or not this capability can be used by NepalMap. If so, the outcome should also include a technical description of how the new capabilities work.

**Comment by ravinepal** [comment]
@cliftonmcintosh - I'm curious if we should have also have census2011.nepalmap.org to archive the pre-federal data as it is?

**Comment by cliftonmcintosh** [comment]
That would certainly be possible, yes.

**Comment by cliftonmcintosh** [comment]
No one has expressed interest in pursuing this issue. If there is no tangible interest, I will close this issue on Dec. 21, 2019.

**Comment by nikeshbalami** [comment]
Both the pre-federal and federal data come from Census 2011.

Closing this issue; because at the end of the day, the data we are using is same and we already have most of the data which are in the pre-federal version.
