### ISSUE TITLE
Add population data of zero for all national parks, hunting and wildlife reserves and development areas

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#38]
National parks, hunting and wildlife reserves and development area have no official population (although I'm sure we all know that someone lives in them). For our purposes, add counts of zero for each national parks, hunting and wildlife reserve and development area in the table below.

Add the data to the [population.sql](https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/population.sql) file. Please put the data in a logical place -- so that all data for the same district are in rows next to each other. That will make it easier to review in the future.

- When you add them, you will add one row for female population and another row for male population. See the current file for examples.

 | geo_level | geo_code |                name                 |   parent_name    | parent_level | parent_code |
-----------|----------|-------------------------------------|------------------|--------------|-------------
 local     | 69099    | Khaptad National Park                    | Achham           | district     | 01
 local     | 45099    | Dhorpatan Hunting Reserve                | Baglung          | district     | 03
 local     | 68099    | Khaptad National Park                    | Bajhang          | district     | 05
 local     | 67099    | Khaptad National Park                    | Bajura           | district     | 06
 local     | 33099    | Parsa Wildlife Reserve                   | Bara             | district     | 08
 local     | 58099    | Bardiya National Park                    | Bardiya          | district     | 09
 local     | 35099    | Chitawan National Park                   | Chitwan          | district     | 12
 local     | 70099    | Khaptad National Park                    | Doti             | district     | 22
 local     | 72099    | Shuklaphanta National Park               | Kanchanpur       | district     | 32
 local     | 31099    | Chitawan National Park                   | Makwanpur        | district     | 41
 local     | 31088    | Parsa Wildlife Reserve                   | Makwanpur        | district     | 41
 local     | 43099    | Dhorpatan Hunting Reserve                | Myagdi           | district     | 46
 local     | 76099    | Chitawan National Park                   | Nawalparasi East | district     | 47
 local     | 28099    | Langtang National Park                   | Nuwakot          | district     | 48
 local     | 28088    | Shivapuri Watershed And Wildlife Reserve | Nuwakot          | district     | 48
 local     | 34099    | Chitwan National Park                    | Parsa            | district     | 53
 local     | 77099    | Dhorpatan Hunting Reserve                | Rukum East       | district     | 59
 local     | 15099    | Koshi Tappu Wildlife Reserve             | Saptari          | district     | 63
 local     | 6099     | Koshi Tappu Wildlife Reserve             | Sunsari          | district     | 69
 local     | 14099    | Koshi Tappu Wildlife Reserve             | Udayapur         | district     | 75
 local     | 49099    | Lumbini Sanskritik Development Area | Rupandehi        | district     | 60

**Comment by cliftonmcintosh** [comment]
SQL query with concatenation to build the data for parks, reserves and development areas:

```
wazimap_np=> select concat(g.geo_code, ',local,male,0', chr(10), g.geo_code, ',local,female,0'), g.name, g.parent_code from wazimap_geography g where name like '%Park%' or name like '%Reserve%' or name like '%Development Area%' order by g.parent_code;
        concat        |                   name                   | parent_code 
----------------------+------------------------------------------+-------------
 69099,local,male,0  +| Khaptad National Park                    | 01
 69099,local,female,0 |                                          | 
 45099,local,male,0  +| Dhorpatan Hunting Reserve                | 03
 45099,local,female,0 |                                          | 
 68099,local,male,0  +| Khaptad National Park                    | 05
 68099,local,female,0 |                                          | 
 67099,local,male,0  +| Khaptad National Park                    | 06
 67099,local,female,0 |                                          | 
 33099,local,male,0  +| Parsa Wildlife Reserve                   | 08
 33099,local,female,0 |                                          | 
 58099,local,male,0  +| Bardiya National Park                    | 09
 58099,local,female,0 |                                          | 
 35099,local,male,0  +| Chitawan National Park                   | 12
 35099,local,female,0 |                                          | 
 70099,local,male,0  +| Khaptad National Park                    | 22
 70099,local,female,0 |                                          | 
 72099,local,male,0  +| Shuklaphanta National Park               | 32
 72099,local,female,0 |                                          | 
 31099,local,male,0  +| Chitawan National Park                   | 41
 31099,local,female,0 |                                          | 
 31088,local,male,0  +| Parsa Wildlife Reserve                   | 41
 31088,local,female,0 |                                          | 
 43099,local,male,0  +| Dhorpatan Hunting Reserve                | 46
 43099,local,female,0 |                                          | 
 76099,local,male,0  +| Chitawan National Park                   | 47
 76099,local,female,0 |                                          | 
 28088,local,male,0  +| Shivapuri Watershed And Wildlife Reserve | 48
 28088,local,female,0 |                                          | 
 28099,local,male,0  +| Langtang National Park                   | 48
 28099,local,female,0 |                                          | 
 34099,local,male,0  +| Chitwan National Park                    | 53
 34099,local,female,0 |                                          | 
 77099,local,male,0  +| Dhorpatan Hunting Reserve                | 59
 77099,local,female,0 |                                          | 
 49099,local,male,0  +| Lumbini Sanskritik Development Area      | 60
 49099,local,female,0 |                                          | 
 15099,local,male,0  +| Koshi Tappu Wildlife Reserve             | 63
 15099,local,female,0 |                                          | 
 6099,local,male,0   +| Koshi Tappu Wildlife Reserve             | 69
 6099,local,female,0  |                                          | 
 14099,local,male,0  +| Koshi Tappu Wildlife Reserve             | 75
 14099,local,female,0 |                                          | 
(21 rows)
```

**Comment by cliftonmcintosh** [comment]
Zeros are not handled well by the wazimap framework. When the numbers are zero, the population section gets messed up.

Here is an example with Langtang National Park:
![langtang-park-zero-display-problem](https://user-images.githubusercontent.com/3824492/49700458-673c1800-fba4-11e8-9ff6-350872bf7136.png)

**Comment by openrijal** [comment]
anything I can do to help here @cliftonmcintosh

**Comment by clifton-mcintosh** [comment]
@crackjack

#40 resolves this issue.
