### ISSUE TITLE
What is correct, "Nawal" and "Parasi" or "Nawalparasi East" and "Nawalparasi West"?

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#39]
Our geographic data uses "Nawalparasi East" and "Nawalparasi West", but our population data has "Nawal" and "Parasi". The wikipedia says that "Nawal" and "Parasi" are the correct names for those districts. Is that accurate? If so, we should create an issue to correct our geographic data.

**Comment by ravinepal** [comment]
Geographic data is correct. 

Nawalparasi East" https://election.ekantipur.com/province-level-results/pradesh-4/district-nawalparasieast?lng=eng

"Nawalparasi West" https://election.ekantipur.com/pradesh-5/district-nawalparasiwest?lng=eng

**Comment by nikeshbalami** [comment]
Basically "Nawalparasi East" and "Nawalparasi West" are the old names. The new and official names are "Nawalpur" and "Parasi", both are not wrong. It depends upon us, we can use any of them.

But I suggest to use new names, so we don't have to update it later.

**Comment by ravinepal** [comment]
thanks, nikesh! is there a gov website that gives the official names of these places? let's go with the official names

**Comment by himalacharya** [comment]
Nawalparasi and Nawalparasi (Bardaghat Susta East)
http://daonawalparasibardhaghatwest.moha.gov.np/en
http://officies.moha.gov.np/?office=daonawalparasibardhaghateast

**Comment by cliftonmcintosh** [comment]
What's the decision here, @nikeshbalami and @ravinepal ? Can you confirm which one we should use?

**Comment by himalacharya** [comment]
> What's the decision here, @nikeshbalami and @ravinepal ? Can you confirm which one we should use?

Nawalparasi and Nawalparasi (Bardaghat Susta West) are official name .. 
![image](https://user-images.githubusercontent.com/16852900/49714648-cf0e6380-fc75-11e8-8d42-5df257094d9d.png)
![image](https://user-images.githubusercontent.com/16852900/49714667-e2b9ca00-fc75-11e8-963c-c0523f937e9d.png)

I take this snapshot from dropdown menu in selecting district name from Election Commission, Nepal. This is in Nepali language

**Comment by openrijal** [comment]
if I am not wrong, there was no east or west before the districts got divided, it was called "Nawalparasi", but after it got split, the official names became "East Nawalparasi" and "West Nawalparasi", west is also known as "susta west", but the common names are "Nawalpur" and "Parasi" respectively.

I think we should just use "East Nawalparasi" and "West Nawalparasi" for clarity.

I'm certain there is also another district, it is "East Rukum" and "West Rukum", I think. It keeps the conformity in the data.

**Comment by openrijal** [comment]
And I agree the "Official Name" for west nawalparasi is "Nawalparasi Bardaghat Susta West", but I think if we remove "Bardaghat and Susta" it would still make the same sense.

also, the district got split recently, the older version of Development Regions and Zones had only 1 district called "Nawalparasi" https://en.wikipedia.org/wiki/Lumbini_Zone

**Comment by code4nepal** [comment]
thank you, @himalacharya and @crackjack. Based on the election commission screenshots, please use Nawalparasi and Nawalparasi (Bardaghat Susta West). I like Nitesh's recommendation - I think for legal purposes we should keep the names as the gov has assigned.
