### ISSUE TITLE
Import geojson and topojson files with the correct metadata for districts

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#4]
Please see the readme at https://github.com/Code4Nepal/nepalmap_federal/tree/master/wazimap_np/static/geo for a description of the metadata needed.

Geojson and topojson files for updating can be downloaded from http://localboundries.oknp.org/

This script was used with the old structure to add to each geojson file the correct metadata: https://github.com/Code4Nepal/maptools/blob/master/geo/set_vdc_geo_properties.py. It may be useful as a sample for what needs doing.

This issue related to #2

**Comment by openrijal** [comment]
I'm assuming that the country.geojson and country.topojson files can be used from the old project, right?

**Comment by cliftonmcintosh** [comment]
@crackjack 

Yes, we should be able to re-use https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/static/geo/country.geojson and https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/static/geo/country.topojson

If the boundaries for districts have not changed, then we can re-use https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/static/geo/district.geojson and https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/static/geo/district.topojson

That would be valuable because we have a lot of district-level data that could then be re-used. The most valuable thing would be keeping the same `geoid`s for each district.

**Comment by openrijal** [comment]
I'm sure the district and district boundaries have changed because we had 75 districts before, but now after the provincial division we have 77 districts.

May be we can have the same `geoid`s by comparing the two geojson and matching the names to extract the `geoid`

**Comment by cliftonmcintosh** [comment]
If the districts are different, then the old data cannot be used and there is no need to keep the same IDs

**Comment by openrijal** [comment]
so whatever I sent is acceptable only if I just remove the oknp files and the scripts, right?

**Comment by openrijal** [comment]
oh, yeah the uppercase names, I'll do that.

**Comment by openrijal** [comment]
PR #9 updated
