### ISSUE TITLE
 Import geojson and topojson files with the correct metadata for local government bodies

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#5]
Please see the readme at https://github.com/Code4Nepal/nepalmap_federal/tree/master/wazimap_np/static/geo for a description of the metadata needed.

Geojson and topojson files for updating can be downloaded from http://localboundries.oknp.org/

This script was used with the old structure to add to each geojson file the correct metadata: https://github.com/Code4Nepal/maptools/blob/master/geo/set_vdc_geo_properties.py. It may be useful as a sample for what needs doing.

This issue depends on #2

**Comment by nikeshbalami** [comment]
As per the previous notification from the users, there are some boundaries error in the Geo and TopoJSON Local Levels file of http://localboundries.oknp.org so it would be great if we can use geo file available at the government website. Previously it was available here: http://ngiip.gov.np/data-center/admin-boundary
