### ISSUE TITLE
Update "About NepalMap" sections

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#50]
The "About NepalMap" sections have been copied over from the pre-federal NepalMap. Review those sections and update them as appropriate.

They can be seen at the bottom of https://nm-fed.eastus.cloudapp.azure.com/ and on the about view at https://nm-fed.eastus.cloudapp.azure.com/about

**Comment by amitness** [comment]
This also seems to be fixed by #59.
