### ISSUE TITLE
Inaccurate total population of 51 million

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#55]
The total population listed for Nepal using our current data set is 51 million. That seems very inaccurate!

Googling shows estimates between 26 and 30 million.

See https://beta.nepalmap.org/profiles/country-NP-nepal/

The inaccurate data are here: https://github.com/Code4Nepal/nepalmap_federal/blob/dev/sql/population.sql#L1750-L1751

### Screenshot

![51-million-population](https://user-images.githubusercontent.com/3824492/52916147-a15f1f80-32a1-11e9-941a-cead1af8a665.png)

**Comment by ravinepal** [comment]
@pratimakandel - would you like to take a look at this and submit a pull request within a week or so if you have time?

**Comment by cliftonmcintosh** [comment]
Fixed by #56 

Thank you, @pratimakandel

**Comment by cliftonmcintosh** [comment]
screenshot after update

![issue-55-population-fix](https://user-images.githubusercontent.com/3824492/52976894-e910a480-3390-11e9-8272-f695f72483c6.png)
