### ISSUE TITLE
Update main page teaser text and "Find facts" text

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#58]
The current description on the main page is 
> Whether you live in Morang or Mahottari, find out how many people in your district have passed School Leaving Certificate (SLC), or how many people still use wood to cook food.

The "Find facts" description should also be revised. It says
> Data is broken down by category: Demographics, education.

These both should be changed to reflect data that we currently provide in the federal version. They can be updated later with new suggested ideas for things to look for. 

![teaser-text](https://user-images.githubusercontent.com/3824492/53687277-683e9a80-3cf8-11e9-97c0-c81fdb9197cd.png)

**Comment by amitness** [comment]
Is this issue fixed by #59? We can close this if so.

**Comment by cliftonmcintosh** [comment]
Yes, I believe #59 addressed this issue.
