### ISSUE TITLE
Update settings.py to include the new federal hierarchy

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#6]
settings.py defines the relationship between entities at different geographic levels. Update it to include definitions that fit the new federal structure.

See here for the old definitions: https://github.com/Code4Nepal/nepalmap_app/blob/dev/wazimap_np/settings.py#L21-L40

Update settings.py so that it includes the new definitions.

**Comment by openrijal** [comment]
Pull Request https://github.com/Code4Nepal/nepalmap_federal/pull/9

**Comment by cliftonmcintosh** [comment]
Covered in #9
