### ISSUE TITLE
Add a link to the original data set for each profile section

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#64]
For each section in the profile, add a link to the original data set to allow users to double-check our work and to provide more accountability and transparency. For example, the Households summary would have a link to the National Data Profile (http://nationaldata.gov.np) underneath the section where the total number of households is shown in NepalMap. Links should be as specific as possible but can be more general when specificity is not possible. For example, we do not currently have the ability to link to the National Data Profile pages for a specific locality or district or province, so a link to the main National Data Profile page is appropriate.

**Comment by amitness** [comment]
@cliftonmcintosh Which of the following is correct?
1. 'source: national data' under each of the chart in the household section.
2. one 'source: national data' only for the whole "household" section

I understood the description as (2).
![image](https://user-images.githubusercontent.com/8587189/63637169-166c4100-c699-11e9-9e4f-8cc5c552ebbe.png)

**Comment by cliftonmcintosh** [comment]
Yes, I agree
> one 'source: national data' only for the whole "household" section

sounds good
