### ISSUE TITLE
Specify "hectare" as unit of measurement in agricultural land holdings statistics

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#69]
The unit of measurement for land holdings is the hectare, but we do not specify what unit we are using. We should update the display so that it states that the units is the hectare.

Current view for land holdings:
![agriculture-without-unit-of-measurement](https://user-images.githubusercontent.com/3824492/63642884-321d1a80-c68c-11e9-8990-71710537d844.png)

Sample with unit specified in old NepalMap (for a different statistic):
![sample-with-unit-specified](https://user-images.githubusercontent.com/3824492/63642882-2d586680-c68c-11e9-9fdd-c2640f047291.png)

**Comment by amitness** [comment]
Solved by #70
