### ISSUE TITLE
Update Homepage (Find facts) content

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap_federal#78]
It says only population data, Since we already have more data now, it will be great to update those text.

![image](https://user-images.githubusercontent.com/3656268/69810298-acbd7f00-1213-11ea-9d96-69c7680e9810.png)

**Comment by nikeshbalami** [comment]
Updated Homepage content is now available here: https://docs.google.com/document/d/1260oj8mpWfliKvFISZb7ZgE7-iBZ28re7mtzao9ddHY/edit?usp=sharing

**Comment by ishandongol** [comment]
thanks for the content. will update it

**Comment by cliftonmcintosh** [comment]
@nikeshbalami and @ishandongol 

Ishan's update to the homepage has been deployed to https://beta.nepalmap.org/.

I have also created issues #89 and #90 as follow ups to that work.

![updated-homepage-20191215](https://user-images.githubusercontent.com/3824492/70864510-5ab97080-1f18-11ea-8afa-a9c9974e755d.png)

**Comment by nikeshbalami** [comment]
Closing this issue, it has been resolved in PR https://github.com/Code4Nepal/nepalmap_federal/pull/93 and https://github.com/Code4Nepal/nepalmap_federal/pull/91
