### ISSUE TITLE
Create top menu icon navigation of available data

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap_federal#79]
South Africa portal (https://wazimap.co.za/profiles/country-ZA-south-africa/) has this beautiful icon navigation located at the top. This will make the data navigation easy because users don't have to scroll through the whole page. Create/Develop something similar for NepalMap.

South Africa display
![image](https://user-images.githubusercontent.com/3656268/69811006-3de12580-1215-11ea-8270-89f85633f89d.png)

NepalMap display
![image](https://user-images.githubusercontent.com/3656268/69811084-68cb7980-1215-11ea-9f0c-6b8f1f4d1d42.png)

**Comment by ishandongol** [comment]
working on it

**Comment by ravinepal** [comment]
Hey @ishandongol - a while ago, @arlexgole had created a modern look and feel for NepalMap. May I ask if you could look into it and implement changes.  I think having navigation on the left side, and Google's Material Design approach would be much user friendly. 

We'd be very grateful for your help. Pls see below

https://github.com/Code4Nepal/nepalmap_app/issues/243#issuecomment-463049728

**Comment by ishandongol** [comment]
Sure, Will look into it.

**Comment by cliftonmcintosh** [comment]
@nikeshbalami I believe this was fulfilled by #80. Can this issue be closed now?

**Comment by nikeshbalami** [comment]
Let's keep this issues alive so that it will be easier for @ishandongol to navigate @ravinepal comment about modernizing the look of NepalMap or we can close this one and create new issues for it: https://github.com/Code4Nepal/nepalmap_app/issues/243

**Comment by nikeshbalami** [comment]
Thank you @ishandongol for working on it and @cliftonmcintosh & @ravinepal for the guidance.

Solved by PR https://github.com/Code4Nepal/nepalmap_federal/pull/80, https://github.com/Code4Nepal/nepalmap_federal/pull/81 & https://github.com/Code4Nepal/nepalmap_federal/pull/97, closing this issue.
