### ISSUE TITLE
Approximately 600000 lower population in in federal version than in pre-federal version

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#82]
The total population for the pre-federal NepalMap and the federal NepalMap both come from the 2011 census. However, the two versions do not agree on the total population. The pre-federal version counts 2,64,94,504 people while the federal version counts almost 6,00,000 fewer: 2,59,07,649.

Any idea why we might have this difference?

Pre-federal version:
![pre-federal population](https://user-images.githubusercontent.com/3824492/69904628-4b5df300-136e-11ea-8c6f-dc829810e250.png)

Federal version:
![federal-population](https://user-images.githubusercontent.com/3824492/69904630-4f8a1080-136e-11ea-86dd-4b9f9b89ef8e.png)

**Comment by ishandongol** [comment]
I have no idea. Nikesh has better idea on that.

**Comment by nikeshbalami** [comment]
We are currently reviewing the data, will ask everyone to check the population data carefully.

**Comment by nikeshbalami** [comment]
Thank you so much @cliftonmcintosh for the heads up, while reviewing we found many errors in population data.

@pratimakandel and I have created a new sheet with updated population data (https://docs.google.com/spreadsheets/d/1hM7vIDtQGG818XNxuRW1_JtFpgx7msmosdjkM3rHfdM/edit?usp=sharing). She will soon update this at NepalMap population SQL to resolve this issue.

**Comment by nikeshbalami** [comment]
Thank you @pratimakandel & @cliftonmcintosh 

Solved by PR https://github.com/Code4Nepal/nepalmap_federal/pull/95, closing this issue.
