### ISSUE TITLE
"Code for Nepal is entirely built..." should be "NepalMap is entirely built..."

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#89]
I believe the text "Code for Nepal is entirely built by volunteers..." should be "NepalMap is entirely built by volunteers..."

https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/templates/homepage.html#L96

I would also suggest we could link to the GitHub contributors for the project: https://github.com/Code4Nepal/nepalmap_federal/graphs/contributors

**Comment by ishandongol** [comment]
@cliftonmcintosh I updated this in #90
