### ISSUE TITLE
about.html text should be updated to match homepage.html text

### ISSUE THREAD

**Issue by cliftonmcintosh** [CodeforNepal/nepalmap_federal#90]
With #78, the text of the homepage was updated. There is an identical section in the `about.html` template: https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/templates/about.html#L4-L24

This should be updated to match the homepage content at https://github.com/Code4Nepal/nepalmap_federal/blob/dev/wazimap_np/templates/homepage.html#L75-L103

**Comment by ishandongol** [comment]
will update that.

**Comment by cliftonmcintosh** [comment]
Completed in #93
