### ISSUE TITLE
Update local levels name at geography.sql

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap_federal#92]
While reviewing the population data, we found many spelling mistakes of local levels name in geography.sql file.

If possible update the SQL file will full name, for example, "Kathmandu" with "Kathmandu Metropolitan City" and so on, this will make the data adding part easier for upcoming days.

Will soon create and share a new sheet with existing geo_code; to discuss the possibilities.

**Comment by nikeshbalami** [comment]
Here goes the sheet with updated/changed name of local levels for SQL file: https://docs.google.com/spreadsheets/d/1Jcqcf2BDT6TqaUO-4HtOapZY0AkKI7Fgy2XR5K6hY-Y/edit?usp=sharing

**Comment by pratimakandel** [comment]
Great! I will test it and submit a pull request.

Sincerely,
Pratima Kandel.

**Comment by nikeshbalami** [comment]
@pratimakandel @cliftonmcintosh 

Here goes the new sheet with the short name at "name" part and official name at "long_name" part. Let's update this at geography.sql table again: https://docs.google.com/spreadsheets/d/1EnnVMf6XzAxiw4qUBwKw683Ie9Z6y9hf5sn07VGgf38/edit?usp=sharing

**Comment by nikeshbalami** [comment]
Thank you @pratimakandel and @cliftonmcintosh 

Solved by PR https://github.com/Code4Nepal/nepalmap_federal/pull/95, Closing this issue.
