### ISSUE TITLE
Update new/current local bodies name at TopoJSON and GeoJSON file

### ISSUE THREAD

**Issue by nikeshbalami** [CodeforNepal/nepalmap_federal#96]
Find a way to update new/current local levels name at TopoJSON and GeoJSON file, so that the new name can be displayed at a map while hovering.

Here is the list of the changed local bodies name: https://docs.google.com/spreadsheets/d/1Y3Na_CEWLHERczUng_lGfpc4jl0qalVAmF3Aioc6VEc/edit?usp=sharing

**Comment by nikeshbalami** [comment]
I believe the name of local bodies in **Map** are still needed to be made as per the above sheet. In https://github.com/Code4Nepal/nepalmap_federal/pull/95#issuecomment-568274043 @cliftonmcintosh suggested writing a script to alert the changed name, rather than changing the whole GEO file.

@pratimakandel @ishandongol do you guys know how to do it, or maybe @cliftonmcintosh if you have some time this weekend, can you help to resolve this issue.

Once this issue is resolved, we can confidently make the site public for the review.

**Comment by cliftonmcintosh** [comment]
@nikeshbalami 

Thanks for the update. My available time is limited right now, and I will be unable to help with this task. @crackjack did the initial work to add the geo codes and names to the JSON files. He may have a script that can be adapted for this work.

**Comment by openrijal** [comment]
Hi Guys. The script I used are still available here: https://github.com/Code4Nepal/maptools/tree/master/geo  

Let me know if I can be of any help.

**Comment by openrijal** [comment]
I would suggest a quick find and replace in this case. Writing a script might be longer than doing it manually.

**Comment by pratimakandel** [comment]
I have created a pull request for this issue, Please let me know if there is anything missing. 
https://github.com/Code4Nepal/nepalmap_federal/pull/99

**Comment by nikeshbalami** [comment]
Closing this issue, solved by PR https://github.com/Code4Nepal/nepalmap_federal/pull/99

Thank you @pratimakandel :)
